### ISSUE TITLE
插件cookiecloud报错

### ISSUE THREAD

**Issue by rehack** [RamenRa/MoviePilot-Plugins#1]
我在mp2使用的插件 动态企微可信IP v1.6.0
配置如图：
![PixPin_2024-12-12_09-49-21](https://github.com/user-attachments/assets/3031c949-8582-4657-99bb-00fd8208993e)
修改IP不成功，查看日志有如下报错
`从CookieCloud获取cookie错误，错误原因:not enough values to unpack (expected 2, got 1)`
![PixPin_2024-12-12_09-47-22](https://github.com/user-attachments/assets/1f5294cc-8c37-4bfa-9a50-4d962e797a5e)

我的CookieCloud是docker搭建的，测试没问题，mp2的同步CookieCloud站点功能也没问题，所以想请教下是我配置是哪里出了问题

**Comment by RamenRa** [comment]
如下图所示我无法复现以上错误，请检查你的CookieCloud配置。如果还是没有解决请围绕CookieCloud的配置提供更详细的设置信息。<br>
* 12:58我让cookie失效后，使用CookieCloud插件重新同步到自定义的CookieCloud服务器。重新在插件调用cookie并没有发生错误。
![0001](https://github.com/user-attachments/assets/b4d6a03d-ed48-4d6d-ab49-070d9fc53d4b)
* 12:59 MP进行同步
![0000](https://github.com/user-attachments/assets/78b93b9d-3cd2-4692-bec8-4fb00677a261)

**Comment by rehack** [comment]
围绕CookieCloud测试都没啥问题
![image](https://github.com/user-attachments/assets/28a0f722-d688-4d89-8bb6-8109ee7d9ff6)

![image](https://github.com/user-attachments/assets/08cb1cb8-c758-4d6d-885c-ed6db9880863)

![image](https://github.com/user-attachments/assets/d157c225-b2d3-4892-8760-c6bfaebb254f)


唯一不一样的地方是我搭建的cookiecloud和你的API地址不一样

**Comment by rehack** [comment]
特意查看mp的cookiecloud日志，也是正常的
![image](https://github.com/user-attachments/assets/471ddec3-9f77-4430-844d-ee222426472f)
此插件可否调试？我想知道插件运行的时候对我的cookiecloud连通性如何

**Comment by RamenRa** [comment]
@rehack 我不用自建的CookieCloud，不是很明白多了`/cookie`会不会有什么影响。目前看来是上传的cookie和windows平台的不一致，没有mac系统我这边不是很好排查。以下是我目前能想到的一些解决思路。以下方案由易到难。
## 可以尝试原仓库
* [原仓库suraxiuxiu](https://github.com/suraxiuxiu/MoviePilot-Plugins/)已更新，目前除了没有配置多个通知和从指定url获取ip外，功能都一样。
## 关于CookieCloud连接性
* 涉及到CookieCloud连接的[代码](https://github.com/RamenRa/MoviePilot-Plugins/blob/master/plugins/dynamicwechat/__init__.py#L319)不多。主要是`__init__.py`中的`try_connect_cc()`和`helper.py`的`check_connection()`检查连接性。重启MP，在插件启用‘本地扫码修改ip’功能就会运行这两个函数，观察日志即可判断连接性。
## 自行debug(需要会修改代码)
* `__init__.py`→`get_cookie()`→`self._cookiecloud.download()`这个函数是MP官方提供的函数。你上传的cookie，插件就是通过这个获取的。
* 尝试[Debug仓库](https://github.com/Rob0088/MoviePilot-Plugins/tree/main/plugins/dydebug)，debug仓库会在日志打印出从CookieCloud获取到的原始数据。根据返回内容做特殊处理。主要在`get_cookie()`函数做处理。
* 可以fork到自己仓库做更多调试，没有mac环境复现不了问题，实在是爱莫能助。
