### ISSUE TITLE
我是双线带宽用户

### ISSUE THREAD

**Issue by chenlu964** [RamenRa/MoviePilot-Plugins#2]
能不能自动检测我2个宽带ip呢，现在好像只能检测一个

**Comment by RamenRa** [comment]
不是很清楚双宽带的网络情况。双宽带不是同一时间只能用一个吗？如果是的话，插件获取的就是mp所用的宽带。这样不是不影响消息发送吗？

**Comment by chenlu964** [comment]
我是一条移动一条电信，爱快随机分流的，可能这条信息是移动下一条信息就是电信收到。然后轮到电信收到消息就用不了了。
解决思路：
能否用多出口检测站点检测，然后把所有国内的ip添加到可信ip里呢

**Comment by chenlu964** [comment]
附上3个多出口检测网址
https://ip.orz.tools/
http://revproxy.ustc.edu.cn:8000
https://ip.skk.moe/multi
![555](https://github.com/user-attachments/assets/2b22488b-0abb-4500-903e-b18c69d648e5)

**Comment by RamenRa** [comment]
@chenlu964 我在[debug仓库](https://github.com/Rob0088/MoviePilot-Plugins)尝试实现，目前没有双公网环境没办法测试。使用方式是在`应用ID`一栏填写`应用ID||wan2`。如果有多个应用依然可以继续使用逗号分隔。如`应用ID1,`应用ID2||wan2`
### 请尽量创建一个新的企业微信应用测试！
目前也还不确定会不会更新到正式版中，也有可能单独一个仓库。
<br>

### 已知的问题
* 每次修改插件配置保存会有6秒左右的延时。
* 获取IP的方式是模拟浏览器打开页面，读取页面元素来获取IP，性能要求会高一点。
* 每个多出口检测网址的元素都不一样，所以无法使用”从指定url获取IP“的功能

**Comment by chenlu964** [comment]
实测还是有点小问题，不是每次都能获取到多IP 附上日志
![111](https://github.com/user-attachments/assets/98d1820d-ccfc-4d71-8551-c509c9ab9a1b)
![222](https://github.com/user-attachments/assets/48628b1e-5698-4e16-b4d6-db085d1d7393)

**Comment by chenlu964** [comment]
我把日志里的ip替换成不存在的ip，然后文字的形式发你看日志好了，只有https://ip.orz.tools:这个获取的时候比较稳，五六次只有一次没获取到多IP，http://revproxy.ustc.edu.cn:8000这个就不行，是不是检测的时间拉长一点会好一点
`
【INFO】2024-12-17 13:20:05,824 - dydebug - ----------------------本次任务结束----------------------
【INFO】2024-12-17 13:20:05,824 - dydebug - IP获取成功: http://revproxy.ustc.edu.cn:8000/: 39.100.100.100
【INFO】2024-12-17 13:20:00,009 - dydebug - 开始检测公网IP
【INFO】2024-12-17 13:10:05,959 - dydebug - ----------------------本次任务结束----------------------
【INFO】2024-12-17 13:10:05,958 - dydebug - IP获取成功: http://revproxy.ustc.edu.cn:8000/: 39.100.100.100
【INFO】2024-12-17 13:10:00,007 - dydebug - 开始检测公网IP
【INFO】2024-12-17 13:00:05,914 - dydebug - ----------------------本次任务结束----------------------
【INFO】2024-12-17 13:00:05,914 - dydebug - IP获取成功: http://revproxy.ustc.edu.cn:8000/: 39.100.100.100
【INFO】2024-12-17 13:00:00,006 - dydebug - 开始检测公网IP
【INFO】2024-12-17 12:50:07,254 - dydebug - ----------------------本次任务结束----------------------
【INFO】2024-12-17 12:50:07,253 - dydebug - IP获取成功: https://ip.orz.tools: 39.100.100.100, 122.200.200.200
【INFO】2024-12-17 12:50:00,009 - dydebug - 开始检测公网IP
【INFO】2024-12-17 12:40:05,887 - dydebug - ----------------------本次任务结束----------------------
【INFO】2024-12-17 12:40:05,886 - dydebug - IP获取成功: http://revproxy.ustc.edu.cn:8000/: 122.200.200.200
【INFO】2024-12-17 12:40:00,009 - dydebug - 开始检测公网IP
【INFO】2024-12-17 12:30:07,400 - dydebug - ----------------------本次任务结束----------------------
【INFO】2024-12-17 12:30:07,399 - dydebug - IP获取成功: https://ip.orz.tools: 39.100.100.100, 122.200.200.200
【INFO】2024-12-17 12:30:00,006 - dydebug - 开始检测公网IP
【INFO】2024-12-17 12:20:05,872 - dydebug - ----------------------本次任务结束----------------------
【INFO】2024-12-17 12:20:05,871 - dydebug - IP获取成功: http://revproxy.ustc.edu.cn:8000/: 39.100.100.100
【INFO】2024-12-17 12:20:00,009 - dydebug - 开始检测公网IP
【INFO】2024-12-17 12:10:13,058 - dydebug - ----------------------本次任务结束----------------------
【INFO】2024-12-17 12:10:13,058 - dydebug - IP获取成功: https://ip.orz.tools: 39.100.100.100, 122.200.200.200
【INFO】2024-12-17 12:10:00,007 - dydebug - 开始检测公网IP
【INFO】2024-12-17 12:00:11,906 - dydebug - ----------------------本次任务结束----------------------
【INFO】2024-12-17 12:00:11,906 - dydebug - IP获取成功: http://revproxy.ustc.edu.cn:8000/: 39.100.100.100
【INFO】2024-12-17 12:00:00,007 - dydebug - 开始检测公网IP
【INFO】2024-12-17 11:50:07,171 - dydebug - ----------------------本次任务结束----------------------
【INFO】2024-12-17 11:50:07,170 - dydebug - IP获取成功: https://ip.orz.tools: 39.100.100.100
【INFO】2024-12-17 11:50:00,007 - dydebug - 开始检测公网IP
【INFO】2024-12-17 11:40:05,930 - dydebug - ----------------------本次任务结束----------------------
【INFO】2024-12-17 11:40:05,929 - dydebug - IP获取成功: http://revproxy.ustc.edu.cn:8000/: 122.200.200.200
【INFO】2024-12-17 11:40:00,006 - dydebug - 开始检测公网IP
【INFO】2024-12-17 11:30:05,895 - dydebug - ----------------------本次任务结束----------------------
【INFO】2024-12-17 11:30:05,894 - dydebug - IP获取成功: http://revproxy.ustc.edu.cn:8000/: 122.200.200.200
【INFO】2024-12-17 11:30:00,010 - dydebug - 开始检测公网IP
【INFO】2024-12-17 11:23:47,872 - dydebug - ----------------------本次任务结束----------------------
【INFO】2024-12-17 11:23:47,764 - dydebug - 应用: 5629501913655853 输入IP：39.100.100.100
【INFO】2024-12-17 11:23:42,402 - dydebug - 登录成功！
【INFO】2024-12-17 11:23:42,337 - dydebug - 检查登录状态...
【INFO】2024-12-17 11:23:40,511 - dydebug - ----------------------本次任务结束----------------------
【INFO】2024-12-17 11:23:40,510 - dydebug - IP获取成功: https://ip.orz.tools: 39.100.100.100
【INFO】2024-12-17 11:23:33,549 - dydebug - 开始检测公网IP
【INFO】2024-12-17 11:23:30,542 - dydebug - 使用Cookie,强制更新公网IP
【INFO】2024-12-17 11:20:07,569 - dydebug - ----------------------本次任务结束----------------------
【INFO】2024-12-17 11:20:07,568 - dydebug - IP获取成功: https://ip.orz.tools: 39.100.100.100, 122.200.200.200
【INFO】2024-12-17 11:20:00,006 - dydebug - 开始检测公网IP`

**Comment by RamenRa** [comment]
@chenlu964  <br>
目前1.7.4版本可以再尝试一下，更新ip的逻辑：最多保存4个IP地址，当url检测出的IP不在4个中则代表需要更新。减少则不管。多检测几轮ip应该就添加全了。

* 请提供http://revproxy.ustc.edu.cn:8000和https://ip.skk.moe/multi界面的截图，先确认这些url都能稳定的获取到你的多个网络出口ip，以便更稳定的获取ip。

### 当前问题
* 第一次检测IP时会失败 ！  
* `立即检测一次`功能无法使用，只能等待检测周期到后检测IP

**Comment by chenlu964** [comment]
1.7.8版本测试了，已成功获取双ip，而且单ip，不会顶掉双IP 我再测试一下 1.7.9版本 再等我1天
![8881](https://github.com/user-attachments/assets/30e54278-3bd6-4e36-a330-9d21ddae0e92)

**Comment by chenlu964** [comment]
1.7.14昨晚测试日志 附上，应该没问题了
[日志.txt](https://github.com/user-attachments/files/18216977/default.txt)

**Comment by RamenRa** [comment]
@RamenRa 不知道这个获取IP的方式会不会被网站限制，或者网站的样式改变就会获取不到ip。为了确保稳定性计划多添加两个url： https://www.itdog.cn/localhost/ 和 https://ip.m27.tech/ ，帮忙看以下这两个url哪个能用。预计本周末在正式版的插件中允许启用`||wan2`这个选项

**Comment by chenlu964** [comment]
https://www.itdog.cn/localhost/  这个检测不了多IP 另外一个可以 附上图片
![11](https://github.com/user-attachments/assets/85929e63-36a1-4fdd-b492-815ca4299ed9)
![22](https://github.com/user-attachments/assets/e1fe26eb-7edb-49bc-8a09-3a0cff7ea673)

**Comment by maikezhao** [comment]
@chenlu964 大佬，为啥我多线路，应用ID哪里填上 应用ID，后面跟上||wan2 就会报错

【INFO】2024-12-25 10:10:00,004 - dynamicwechat - ----------------------本次任务结束----------------------
【ERROR】2024-12-25 10:10:00,004 - dynamicwechat - 获取IP失败 不操作可信IP
【WARNING】2024-12-25 10:10:00,003 - dynamicwechat - wan2 获取IP失败, Error: Invalid URL 'wan2': No scheme supplied. Perhaps you meant https://wan2?
【INFO】2024-12-25 10:10:00,001 - dynamicwechat - 开始检测公网IP
【INFO】2024-12-25 10:00:00,011 - dynamicwechat - ----------------------本次任务结束----------------------
【ERROR】2024-12-25 10:00:00,010 - dynamicwechat - 获取IP失败 不操作可信IP
【WARNING】2024-12-25 10:00:00,009 - dynamicwechat - wan2 获取IP失败, Error: Invalid URL 'wan2': No scheme supplied. Perhaps you meant https://wan2?
【INFO】2024-12-25 10:00:00,007 - dynamicwechat - 开始检测公网IP

**Comment by RamenRa** [comment]
@maikezhao 因为debug版本才支持这个参数
