### ISSUE TITLE
关于COOKIE失效后，导致定时不检测公网IP的问题

### ISSUE THREAD

**Issue by l429609201** [RamenRa/MoviePilot-Plugins#3]
![QQ20241219-190115](https://github.com/user-attachments/assets/7a9d5ea5-b026-4392-86e4-bf81e3c172f4)
--
 如上图所示，在cookie失效后，虽然有cron定时轮询，但是出现了不检测公网IP是否变动问题。我观察了两天，因为企业微信的cookie总是失效的很快，CookieCloud也不会保活很久，就会出现一个问题，就是如果cookie失效了，插件就因为cookie失效而不检测公网IP，导致真正公网IP变动的时候无法及时通知，仅会在重启mp的时候通知一下
--
作者大大，我提个我个人的看法，企业微信的cookie最重要的还是变动的时候可以更改可信IP使用，未变动的时候我觉得是否失效其实意义不大，如果可以的话，应该是做一个上次更新至企业微信的IP和本次检测公网IP的IP做比较，如果有变动，在通知需要更改企业微信可信IP这样会不会好点？

**Comment by RamenRa** [comment]
总体意思是：如果当前IP和上次更新的IP对比有变动，再发通知对吧。<br>
可是IP都已经变了，企业微信不是已经发不出消息了吗？怎么通知呢？修改可信IP靠的就是cookie，cookie失效，插件就没有任何实际作用。
* cookie失效快受什么因素影响还是个谜，我最多25天都没失效。期间公网IP两天变动一次

**Comment by l429609201** [comment]
> 总体意思是：如果当前IP和上次更新的IP对比有变动，再发通知对吧。 可是IP都已经变了，企业微信不是已经发不出消息了吗？怎么通知呢？修改可信IP靠的就是cookie，cookie失效，插件就没有任何实际作用。
> 
> * cookie失效快受什么因素影响还是个谜，我最多25天都没失效。期间公网IP两天变动一次
cookie失效这个问题我也觉得奇怪，我的有时候几个小时就失效了
通知这一块，我觉得可以通过其他的通知方式进行通知和提醒（使用企业微信通知的方式来通知的话，在可信IP不正确的情况下是无法推送的）。比方我说我使用了server酱3+server酱的方法，在cookie失效期间，假设IP出现了变动，通过server酱3通知IP变动和cookie失效并且用server酱推送更新企业微信cookie的二维码（我个人想法是推送一次二维码）毕竟第一时间不是谁都能看到那个消息，等到看到的时候失效的话，还可以通过/push_qr来重新推送。而我现在遇到问题就是在IP变动的情况下，cookie过期了不会通知我去更新cookie然后在更新可信IP

**Comment by RamenRa** [comment]
![屏幕截图_20241220_143234](https://github.com/user-attachments/assets/8c406fc7-9637-4b35-bfe9-1ea750c9485a)
ip变动后通知功能，初步在[debug仓库](https://github.com/Rob0088/MoviePilot-Plugins)中实现，可以先测试一下。
* 没问题的话可以再回复一下。以便和正在测试的多网络出口检测一起提交。
### 只有配置了第三方通知才会有"IP变动后通知"按钮！

**Comment by l429609201** [comment]
> ![屏幕截图_20241220_143234](https://private-user-images.githubusercontent.com/53000259/397638814-8c406fc7-9637-4b35-bfe9-1ea750c9485a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ2ODczNzgsIm5iZiI6MTczNDY4NzA3OCwicGF0aCI6Ii81MzAwMDI1OS8zOTc2Mzg4MTQtOGM0MDZmYzctOTYzNy00YjM1LWJmZTktMWVhNzUwYzk0ODVhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjIwVDA5MzExOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdhNzAwNmUxYTM2ZjEzYWE3MWExODg4OTNmNTc0YmU5OWQzOTYxOWE4MjUxOTgwYjY1NGVlNjQwOGUyZjk0Y2MmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.sOAKBWoEJmEdPuhjkLjmHWmGb4qqH0AF1r0sF0PgtPE) ip变动后通知功能，初步在[debug仓库](https://github.com/Rob0088/MoviePilot-Plugins)中实现，可以先测试一下。
> 
> * 没问题的话可以再回复一下。以便和正在测试的多网络出口检测一起提交。
> 
> ### 只有配置了第三方通知才会有"IP变动后通知"按钮！

![1ef2818b-03b4-4654-8b86-ad4eb6fc8bb4](https://github.com/user-attachments/assets/8ed688c2-355f-4695-8819-064afbc4568b)
--
 作者大大，我刚才通过重新拨号获取新的公网IP的方式，模拟公网IP变动的情况，如上图所示，但是还是存在问题，日志中执行到检测到IP变化后就无后续动作了

**Comment by RamenRa** [comment]
1.7.13已拟修复，环境不允许。未验证

**Comment by l429609201** [comment]
已更新的debug版本1.7.13，测试使用下来没有问题，在cookie失效的情况下，如果IP有变动，可正常通过第三方通知方式通知
