### ISSUE TITLE
动态企微可信IP启动报错

### ISSUE THREAD

**Issue by HalcyonDaysssss** [RamenRa/MoviePilot-Plugins#4]
<img width="1028" alt="image" src="https://github.com/user-attachments/assets/a1248357-523f-4be6-af41-6144ae96a859" />
<img width="1571" alt="image" src="https://github.com/user-attachments/assets/dffbaa93-8038-4871-9c67-b42f8ba3fb54" />

**Comment by RamenRa** [comment]
启动浏览器时权限报错，在插件层面无法解决。检查映射到mp的目录权限，检查mp内置浏览器模块是否完全下载(首次部署MP时会自动下载)。
