### ISSUE TITLE
'NoneType' object has no attribute 'reset_limit' ,错误

### ISSUE THREAD

**Issue by Lxy521031** [RamenRa/MoviePilot-Plugins#5]
![image](https://github.com/user-attachments/assets/bb497e4a-31f3-46a7-b0b5-5dca8aaa21c7)
更新 IP 和扫码登录出现错误

**Comment by Lxy521031** [comment]
![image](https://github.com/user-attachments/assets/dab88372-7b60-4beb-b8f4-6f1d96610e1c)
强制更新 IP 一样结果

**Comment by RamenRa** [comment]
可能是没有配置任何通知方式，却调用的通知类的方法。导致的错误。预计1.7.1更新后调用前先检查。

**Comment by Lxy521031** [comment]
填入通知方式后正常
![image](https://github.com/user-attachments/assets/d380bcf1-7ecd-474c-b5b2-e21ebbf08b97)
