### ISSUE TITLE
大佬，啥时候正式版能支持检测多网络出口。

### ISSUE THREAD

**Issue by maikezhao** [RamenRa/MoviePilot-Plugins#6]
我现在是多线路，基于VLAN的混合模式的拨号，有多个宽带ip的，一直在那里切换。

**Comment by RamenRa** [comment]
周末结束前。
* 拟定更新后和当前debug仓库1.8.12版本一致。可以先尝试一下该仓库，如有问题还可以修正。更新后才发现的话估计要多等一周才能修正。
* 没有多线路网络的测试环境。访问以下url能获取到多线路的ip才能使用。
https://ip.orz.tools/
https://ip.m27.tech/ 
https://ip.skk.moe/multi
